spring:
  application:
    name: unerp

  datasource:
    url: jdbc:mysql://localhost:3306/erp_db
    username: erp_user
    password: erp1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
